name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "DD to Torrent"
  comment: "An AI model for creating deep fakes"
  url: "https://www.dropbox.com/scl/fi/3sbfya10oejxton5t19l2/Never-gonna-give-you-up.mp4?rlkey=d2mnm8wm2qzequgui997e8wi9&st=oubgllia&dl=1"
  file_name: "DD to Torrent.mp4"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
